---
apiVersion: v1
kind: Service
metadata:
  name: ad2
  namespace: default
spec:
  selector:
    app: ad2
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
    name: http
  - protocol: UDP
    port: 53
    targetPort: 53
    name: dns
  type: LoadBalancer
