---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  chart:
    spec:
      chart: longhorn
      sourceRef:
        kind: HelmRepository
        name: longhorn
      version: 1.7.2
  interval: 1m0s
  values:
    defaultSettings:
      backupTarget: "nfs://nixnas.joejad.lan:/home/joejad"
