---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: jellyfin-claim
  namespace: jellyfin
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
