---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: home-assistant
  namespace: default
spec:
  selector:
    matchLabels:
      app: home-assistant
  replicas: 1
  progressDeadlineSeconds: 600
  revisionHistoryLimit: 2
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: home-assistant
    spec:
      containers:
        - name: home-assistant
          image: homeassistant/home-assistant:2025.3.1
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          ports:
            - containerPort: 8123
          env:
            - name: TZ
              value: "US/Chicago"
          volumeMounts:
            - mountPath: /config
              name: home-assistant-content
        - name: matter-server
          image: ghcr.io/home-assistant-libs/python-matter-server:7.0.1
          volumeMounts:
            - mountPath: /data
              name: matter-content
      volumes:
        - name: home-assistant-content
          persistentVolumeClaim:
            claimName: home-assistant-claim
        - name: matter-content
          persistentVolumeClaim:
            claimName: matter-claim
      hostNetwork: true
