---
apiVersion: v1
kind: Secret
type: kubernetes.io/basic-auth
data:
  username: cG9zdGdyZXM=
  password: SGdHaWFhMGdRUHh3UXo=
metadata:
  name: pg-superuser
  namespace: default
---
apiVersion: v1
kind: Secret
type: kubernetes.io/basic-auth
data:
  username: am9lamFk
  password: N3JIbzhKcUNRMlJuV3E=
metadata:
  name: pg-app-user
  namespace: default
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres
  namespace: default
spec:
  instances: 3
  superuserSecret:
    name: pg-superuser
  enableSuperuserAccess: true
  postgresql:
    pg_hba:
    - host all all 10.0.0.0/8 scram-sha-256
  bootstrap:
  imageName: "ghcr.io/cloudnative-pg/postgresql:17.1"
  storage:
    size: 10Gi
    storageClass: longhorn
  monitoring:
    enablePodMonitor: true
