---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mealie-claim
  namespace: default
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
