---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: unifi
  namespace: default
spec:
  selector:
    matchLabels:
      app: unifi
  replicas: 1
  progressDeadlineSeconds: 600
  revisionHistoryLimit: 2
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: unifi
    spec:
      containers:
        - name: unifi
          image: lscr.io/linuxserver/unifi-network-application:9.0.114-ls82
          envFrom:
            - secretRef:
                name: unifi-secret
          ports:
          - containerPort: 8443
          - containerPort: 3478
            protocol: UDP
          - containerPort: 10001
            protocol: UDP
          - containerPort: 8080
          - containerPort: 1900
            protocol: UDP
          volumeMounts:
            - mountPath: /config
              name: unifi-config
        - name: unifi-db
          image: docker.io/mongo:4.4
          volumeMounts:
            - mountPath: /data/db
              name: unifi-db-data
            - mountPath: /docker-entrypoint-initdb.d/init-mongo.sh
              name: unifi-db-script
              subPath: init-mongo.sh
          envFrom:
            - secretRef:
                name: unifi-db-secret
      volumes:
        - name: unifi-config
          persistentVolumeClaim:
            claimName: unifi-config-claim
        - name: unifi-db-data
          persistentVolumeClaim:
            claimName: unifi-db-data-claim
        - name: unifi-db-script
          configMap:
            name: unifi
      hostNetwork: true
