---
apiVersion: v1
kind: Service
metadata:
  name: readarr
  namespace: default
spec:
  type: ExternalName
  externalName: 10.47.59.25
  ports:
    - name: http
      port: 8787
      targetPort: 8787
