---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gitea
  namespace: default
spec:
  chart:
    spec:
      chart: gitea
      version: 11.0.0
      sourceRef:
        kind: HelmRepository
        name: gitea
        namespace: default
      interval: 12h
  interval: 30m
  values:
    service:
      http:
        type: ClusterIP
        port: 3000
        clusterIP:
      ssh:
        type: ClusterIP
        port: 2222
        clusterIP:

    postgresql:
      enabled: false
    postgresql-ha:
      enabled: false

    gitea:
      config:
        server:
          SSH_DOMAIN: git.joejad.com
          SSH_PORT: 2222
      additionalConfigSources:
        - secret:
            secretName: gitea-database
