---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - adguard
  - change
  - external
  - freshrss
  - gitea
  - gluetun
  - grafana
  - home-assistant
  - homepage
  - jellyfin
  - longhorn
  - mealie
  - minecraft
  - nextcloud
  - pdf
  - postgres
  - scrypted
  - traefik
  - unifi
  - vault
