---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: local-joejad-com
  namespace: default
spec:
  secretName: local-joejad-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "*.joejad.com"
  dnsNames:
  - "joejad.com"
  - "*.joejad.com"
