---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jellyfin
  namespace: jellyfin
spec:
  selector:
    matchLabels:
      app: jellyfin
  replicas: 1
  progressDeadlineSeconds: 600
  revisionHistoryLimit: 2
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: jellyfin
    spec:
      nodeName: agent-3
      containers:
        - name: jellyfin
          image: "jellyfin/jellyfin:10.10.6"
          ports:
            - containerPort: 8096
          securityContext:
            privileged: true
          env:
            - name: JELLYFIN_PublishedServerURL
              value: "https://jellyfin.joejad.com"
          volumeMounts:
            - mountPath: /config
              name: jellyfin-content
            - mountPath: /cache
              name: jellyfin-content
            - mountPath: /media
              name: jellyfin-media
            - name: "render-device"
              mountPath: "/dev/dri/renderD128"
      volumes:
        - name: jellyfin-content
          persistentVolumeClaim:
            claimName: jellyfin-claim
        - name: jellyfin-media
          nfs:
            server: nixnas.joejad.lan
            path: /home/joejad/media
        - name: "render-device"
          hostPath:
            path: "/dev/dri/renderD128"
      hostNetwork: true
